### ISSUE TITLE
Task creation with owner address returns CANCELLED error instead of invalid address

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/ava-sdk-js#16]
### Expected Behavior
- The API should reject task creation when using an owner address instead of a smart wallet address
- Should throw an "invalid address" error

### Current Behavior
- Instead of receiving an "invalid address" error, the API call is cancelled
- Receiving error: "1 CANCELLED: Call cancelled"

### Test Details
```typescript
test("should fail when creating a task with owner address using API key", async () => {
  await expect(
    client.createTask({
      address: ownerAddress,
      tokenContract: TOKEN_CONTRACT,
      oracleContract: ORACLE_CONTRACT,
    })
  ).rejects.toThrow("invalid address");
});
```

### Test Trace
```
 FAIL  tests/createTask.test.ts
  ● listTasks Tests › Auth with API key › should fail when creating a task with owner address using API key

    expect(received).rejects.toThrow(expected)

    Expected substring: "invalid address"
    Received message:   "1 CANCELLED: Call cancelled"

          4576 |   _callRPC(method, request) {
          4577 |     return new Promise((resolve, reject) => {
        > 4578 |       this.rpcClient[method].bind(this.rpcClient)(
```

### Reproduction Steps
1. Run `npx jest -t "should fail when creating a task with owner address using API key"`
2. Observe that instead of receiving an "invalid address" error, the call is cancelled

### Additional Context
- The error occurs at the gRPC client layer rather than reaching the API validation
- This might indicate an issue with error handling in the API key authentication flow
- The test expects a validation error but receives a connection/cancellation error instead

**Comment by v9n** [comment]
Fixed in https://github.com/AvaProtocol/ava-sdk-js/pull/30
