### ISSUE TITLE
Test failure: 3/5 tests failed for createTask.test.ts

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/ava-sdk-js#17]
### Expected Behavior
1. Task creation with owner address should fail with "invalid address" error (both API key and signature auth)
2. Task creation with smart wallet should succeed when using API key auth

### Current Behavior
Three tests are failing with different issues:

1. **Signature Auth + Owner Address**
   - Expected: Should reject with "invalid address"
   - Actual: Successfully creates task with ID "29015"

2. **API Key Auth + Smart Wallet**
   - Expected: Should successfully create task
   - Actual: Fails with "1 CANCELLED: Call cancelled"

3. **API Key Auth + Owner Address**
   - Expected: Should reject with "invalid address"
   - Actual: Fails with "1 CANCELLED: Call cancelled"

### Test Details
```typescript
// Test 1 - Incorrectly succeeding
test("should fail when creating a task with owner address using signature", async () => {
  await expect(
    client.createTask({
      address: ownerAddress,
      tokenContract: TOKEN_CONTRACT,
      oracleContract: ORACLE_CONTRACT,
    })
  ).rejects.toThrow("invalid address");
});

// Test 2 - Failing with cancellation
test("should create a task when authenticated with API key", async () => {
  const result = await client.createTask({
    address: smartWallet,
    tokenContract: TOKEN_CONTRACT,
    oracleContract: ORACLE_CONTRACT,
  });
  expect(result).toBeDefined();
});

// Test 3 - Wrong error type
test("should fail when creating a task with owner address using API key", async () => {
  await expect(
    client.createTask({
      address: ownerAddress,
      tokenContract: TOKEN_CONTRACT,
      oracleContract: ORACLE_CONTRACT,
    })
  ).rejects.toThrow("invalid address");
});
```

### Test Trace
```
 FAIL  tests/createTask.test.ts
  listTasks Tests
    ✓ should throw error when creating a task without authentication (1178 ms)
    Auth with Signature
      ✓ should create a task when authenticated with signature (285 ms)
      ✕ should fail when creating a task with owner address using signature (259 ms)
    Auth with API key
      ✕ should create a task when authenticated with API key (161 ms)
      ✕ should fail when creating a task with owner address using API key (1250 ms)
```

### Reproduction Steps
1. Run `npx jest tests/createTask.test.ts`
2. Observe multiple failures with inconsistent behaviors

### Additional Context
- API key authentication seems to have connection issues (CANCELLED errors)
- Address validation is not working as expected with signature authentication
- The system needs consistent behavior for owner address rejection across both auth methods

**Comment by v9n** [comment]
Fixed in https://github.com/AvaProtocol/ava-sdk-js/pull/30
