### ISSUE TITLE
listTasks should return the majority of task data instead of just id and status

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/ava-sdk-js#28]
There would be many subsequent calls if we need to fetch eash task after getting a list. The listTasks() endpoint should already return the most important data for each task. 

1. According to the below design we would at least need to return Id, creator(SmartAccountAddress), startAt, expiredAt and status fields. 
2. No need to return the eoa wallet address as owner, since we can find it out at the applicate level. Let’s return the direct owner, which is the smart wallet address.
3. @v9n, for simplicity I suggest we return the entire task data in listTasks for now, and trim the response later, when request load increases. 

![CleanShot 2024-11-05 at 01 22 14@2x](https://github.com/user-attachments/assets/50e214b1-84da-4f26-b62b-1be57bc35ce1)

**Task Definition:**
https://github.com/AvaProtocol/ava-sdk-js/blob/main/src/task.ts

**Comment by v9n** [comment]
Fixed in https://github.com/AvaProtocol/ava-sdk-js/pull/30
