### ISSUE TITLE
Create functional tests to cover multiple operations, such as delete and get a task

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/ava-sdk-js#5]

**Comment by v9n** [comment]
Is this test enough ? https://github.com/AvaProtocol/ava-sdk-js/blob/main/tests/basic.test.ts#L196-L207

It peform create, delete, then get and make sure the get failed.

**Comment by chrisli30** [comment]
Yep, that’s the scenario for Get after Delete. Marking this completed for now. by the "deleteTask" in /basic.test.ts
